/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_MANIFEST_SHA256 =
  'e0588e6913e52c09c9d88b0370aab424bace2df14d95836705b624658cacacfa';
// Re-enable only after replacement pools are deployed and their evidence is verified.
export const ALLOW_PRIVATE_BALANCE_DEVELOPMENT_FIXTURE = false;
