/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_CATALOGUE_SHA256 =
  'a62f61198d9165372a07d9fdeba128b249089101fc161cfd3b6a76059b0e0726';
