/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_MANIFEST_SHA256 =
  '5fe754c10f1ddeaa0364fc216a95f053cc91a21fd3fc51dd473ffbd5bc00cd36';
// This exact hash-pinned development deployment is explicitly enabled on Testnet.
export const ALLOW_PRIVATE_BALANCE_DEVELOPMENT_FIXTURE = true;
