/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_CATALOGUE_SHA256 =
  '9f794d75119a179158657199588539fb982f7013880bd441eaf23ca60dc00da3';
