/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_CATALOGUE_SHA256 =
  'af7209ea662f80f5c2dba6f37f9f96eedbc68e923c636c86e00dc75542d63ead';
