/** Generated by protocol/private-balance/scripts/generate-manifest.mjs. */
export const EXPECTED_PRIVATE_BALANCE_MANIFEST_SHA256 =
  'd2e732e31ada4fcf4b62ce8aacb20c198a690a3d9b2ddea1f31c37b05592d83f';
// This exact hash-pinned development deployment is explicitly enabled on Testnet.
export const ALLOW_PRIVATE_BALANCE_DEVELOPMENT_FIXTURE = true;
