import { chromium } from "playwright";
const SP = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 2 });
await p.goto(`file://${SP}/stellarkey-legal.html#security`, { waitUntil: "networkidle" });
await p.waitForTimeout(500);
await p.evaluate(() => document.getElementById("security-leaves")?.scrollIntoView({ block: "start" }));
await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/promo/sec-leaves.png" });
await p.evaluate(() => document.getElementById("security-threat")?.scrollIntoView({ block: "start" }));
await p.waitForTimeout(400);
await p.screenshot({ path: "/tmp/promo/sec-threat.png" });
await b.close();
